# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='is_station',
        ),
        migrations.AlterField(
            model_name='leavesegment',
            name='leave_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.LeaveType'),
        ),
    ]
