# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20181004_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesegment',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
