# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leavesegment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='requires_address',
            field=models.BooleanField(default=False),
        ),
    ]
